// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDUa8xdHym1qQiBz5h-LsEJG1fIBykcCo',
    appId: '1:259215641596:web:f564a05a87d76dbb964079',
    messagingSenderId: '259215641596',
    projectId: 'mobsysucloud-aufgabe2',
    authDomain: 'mobsysucloud-aufgabe2.firebaseapp.com',
    storageBucket: 'mobsysucloud-aufgabe2.firebasestorage.app',
    measurementId: 'G-4JVE22QT5B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHP_XcTCLW34xIOPcxwP1NbiBvElCNnfo',
    appId: '1:259215641596:android:e3b1aad8dbae0d7e964079',
    messagingSenderId: '259215641596',
    projectId: 'mobsysucloud-aufgabe2',
    storageBucket: 'mobsysucloud-aufgabe2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByIsXmAb9DNw7BDacduYW9C8sGvoxoHOw',
    appId: '1:259215641596:ios:5a2eea75b437ca8a964079',
    messagingSenderId: '259215641596',
    projectId: 'mobsysucloud-aufgabe2',
    storageBucket: 'mobsysucloud-aufgabe2.firebasestorage.app',
    iosBundleId: 'com.example.flutterEmptyApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByIsXmAb9DNw7BDacduYW9C8sGvoxoHOw',
    appId: '1:259215641596:ios:5a2eea75b437ca8a964079',
    messagingSenderId: '259215641596',
    projectId: 'mobsysucloud-aufgabe2',
    storageBucket: 'mobsysucloud-aufgabe2.firebasestorage.app',
    iosBundleId: 'com.example.flutterEmptyApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDUa8xdHym1qQiBz5h-LsEJG1fIBykcCo',
    appId: '1:259215641596:web:f14fed30e2fbeef4964079',
    messagingSenderId: '259215641596',
    projectId: 'mobsysucloud-aufgabe2',
    authDomain: 'mobsysucloud-aufgabe2.firebaseapp.com',
    storageBucket: 'mobsysucloud-aufgabe2.firebasestorage.app',
    measurementId: 'G-2J0C2QJNVG',
  );
}
